apiVersion: v1
kind: Service
metadata:
  name: svc-nlm-react
  namespace: default
spec:
  type: NodePort
  selector:
    app: app-nlm-react
  ports:
    - port: 80
      targetPort: 6092
      protocol: TCP
